name: Deploy PHP App

on:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.php'
      - 'model/**'
      - 'view/**'
      - 'controller/**'
      - 'estilos.css'
      - 'style.css'
      - '!README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /var/www/html/mvc_project
            git pull --ff-only
            # Recargar Apache o PHP-FPM si está disponible
            if command -v systemctl >/dev/null 2>&1; then
              sudo systemctl reload apache2 || sudo systemctl restart php-fpm || true
            fi
